### ISSUE TITLE
Add support for nested variogram models.

### ISSUE THREAD

**Issue by unageek** [polatory/polatory#51]
## Phase 1

Integrate anisotropy into RBF definition.

- [x] Add an affine transformation which transforms the RBF to `rbf_base`
- [x] Change the parameter type of `rbf_base::evaluate` from `double` to `const geometry::vectors3d&` (still translation invariant)
- [x] Do affine transformation of points in the following classes
    - `fmm_evaluator`
    - `fmm_operator`
- [x] Remove transformation from `interpolant`

## Phase 2

Move the nugget parameter from RBF to `model`.

- [x] Add `nugget` parameter to `model` and remove from RBFs
- [x] Modify `variogram_fitting` to take `model` instead of `covariance_function_base`

## Phase 3

~Remove the range parameter from covariance functions (which can be specified by a transformation)~

See my [comment](https://github.com/polatory/polatory/pull/62#issuecomment-516719371) in #62.

## Phase 4

Extend `model` to support multiple RBFs.

- [x] Extend `model` class to take multiple RBFs
    But keep the single-RBF ctor for convenience.
- [x] Add `cpd_order()` function to `model` which returns the maximum order of CPD of the RBFs
- [x] Modify `variogram_fitting`
- [x] Modify example programs

RandomFields has [`RMplus`](https://www.rdocumentation.org/packages/RandomFields/versions/3.1.36/topics/RMplus) for this purpose.
