### ISSUE TITLE
Refactor representation of numerical data

### ISSUE THREAD

**Issue by mizuno-gsinet** [polatory/polatory#9]
## Motivation

Currently, we use `std::vector<Eigen::Vector3d>` for points and `Eigen::VectorXd` for values. This is inconsistent and rather inconvenient as the former is a container works with STL algorithms while the latter is not.

However, we can incorporate STL algorithms with Eigen's matrices indirectly; first, apply the algorithm on the index array (`std::vector<size_t>`), then create a transformed copy of the matrix in a similar manner to [NumPy's fancy indexing](https://docs.scipy.org/doc/numpy-1.13.0/user/basics.indexing.html#index-arrays).

Eigen is necessary for doing linear algebra in a productive manner. Therefore it's better to represent all numerical data with Eigen's matrices.

## Possible representations

An array of points and values can be represented by either a row vector or a column vector. Row vectors are relatively unintuitive and harder to work with, in the context of linear algebra (e.g. u.dot(v) will be `u * v.adjoint()` and not `u.adjoint() * v`). We thus adopt the column vectors.

| Representation | Point / Vector | Points / Vectors                       | Values        |
| -------------- | -------------- | -------------------------------------- | ------------- |
| (Current)      | `Vector3d`     | `std::vector<VectorXd>`                | `VectorXd`    |
| Column vector  | `RowVector3d`  | `Matrix<double, Dynamic, 3, RowMajor>` | `VectorXd`    |
| Row vector     | `Vector3d`     | `Matrix<double, 3, Dynamic>`           | `RowVectorXd` |

## Tasks

- [x] Add following typedefs

      using valuesd = Eigen::VectorXd;
      using vector3d = Eigen::RowVector3d;
      using vectors3d = Eigen::Matrix<double, Eigen::Dynamic, 3, Eigen::RowMajor>;
      using point3d = vector3d;
      using points3d = vectors3d;

- [x] Replace in code
      
      | Replace                        | with                                |
      | ------------------------------ | ----------------------------------- |
      | `Eigen::Vector3d`              | `point3d`                           |
      | `std::vector<Eigen::VectorXd>` | `points3d`                          |
      | `for (auto& p : points)`       | `for (auto p : row_range(points))`  |
      | `points.size()`                | `points.rows()`                     |
      | `points[i] / points.at(i)`     | `points.row(i)`                     |
      | `points.push_back(p)`          | Assignment to a shaped matrix       |

- [x] Fix usage of STL algorithms

- [x] Remove `vector_range_view` and `vector_view`

## [Future] Dataframes for API

- Dataframes as in R and Pandas would be handy for an application
- Dataframes are also suitable for reading/writing a CSV table with a user-defined schema
- Row names are not necessary
- `double` is the only necessary data type
- Methods to extract points and values from a dataframe are needed

### Dealing with missing (NA) values

- To incorporate inequality constraints in a dataframe, NA values must be represented
- [Pandas represents NA values by `np.nan`](https://pandas.pydata.org/pandas-docs/stable/missing_data.html)
- Using NaN for NA values could be accepted, as long as the semantics stays consistent
- An alternative would be to use mask arrays
